const errType = {
  userFormateError: {
    status: 400,
    code: 10001,
    message: "用户名或密码为空",
    result: "",
  },
  userAlreadyExited: {
    status: 409,
    code: 10002,
    message: "用户已经存在",
    result: "",
  },
  userRegisterError: {
    status: 500,
    code: 10003,
    message: "用户注册失败",
    result: "",
  },
  userDoesNotExit: {
    status: 409,
    code: 10004,
    message: "用户不存在",
    result: "",
  },
  userLoginError: {
    status: 500,
    code: 10005,
    message: "用户登录失败",
    result: "",
  },
  invalidPassword: {
    status: 409,
    code: 10006,
    message: "密码错误",
    result: "",
  },
  userLoginError: {
    status: 500,
    code: 10007,
    message: "用户登录失败",
    result: "",
  },
  tokenExpiredError: {
    status: 409,
    code: 10101,
    message: "用户token过期",
    result: "",
  },
  invalidToken: {
    status: 409,
    code: 10102,
    message: "用户token无效",
    result: "",
  },
  hadNotAdminPermission: {
    status: 403,
    code: 10103,
    message: "用户没有访问权限",
    result: "",
  },
  updatePwdError: {
    status: 500,
    code: 10201,
    message: "修改密码失败",
    result: "",
  },
  fileUploadError: {
    status: 500,
    code: 10301,
    message: "图片上传失败",
    result: "",
  },
  goodsFormatError: {
    status: 409,
    code: 10302,
    message: "商品信息格式错误",
    result: "",
  },
  publishGoodsError: {
    status: 500,
    code: 10303,
    message: "上传商品信息失败",
    result: "",
  },
  invalidGoodsID: {
    status: 500,
    code: 10304,
    message: "更新商品信息失败",
    result: "",
  },
  addGoodsToCartError: {
    status: 500,
    code: 10401,
    message: "添加商品到购物车失败",
    result: "",
  },
  getCartGoodsError: {
    status: 500,
    code: 10402,
    message: "获取购物车商品失败",
    result: "",
  },
  cartFormatError: {
    status: 409,
    code: 10403,
    message: "购物车参数格式错误",
    result: "",
  },
  deleteCartsError: {
    status: 500,
    code: 10404,
    message: "删除购物车信息失败",
    result: "",
  },
  addressFormatError: {
    status: 409,
    code: 10501,
    message: "地址参数格式错误",
    result: "",
  },
  getAllAddressError: {
    status: 500,
    code: 10502,
    message: "获取地址信息失败",
    result: "",
  },
  updateAddressError: {
    status: 500,
    code: 10503,
    message: "更新地址信息失败",
    result: "",
  },
  deleteAddressError: {
    status: 500,
    code: 10504,
    message: "删除地址失败",
    result: "",
  },
  orderFormatError: {
    status: 409,
    code: 10501,
    message: "订单参数格式错误",
    result: "",
  },
  getAllOrderError: {
    status: 500,
    code: 10502,
    message: "获取订单信息失败",
    result: "",
  },
  updateOrderError: {
    status: 500,
    code: 10503,
    message: "更新订单信息失败",
    result: "",
  },
};

module.exports = errType;
